# website-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-content
        configMap:
          name: website-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Simple Website</title>
    </head>
    <body>
        <h1>Welcome to the Simple Website!</h1>
        <p>This is a basic example of a website running on Kubernetes.</p>
    </body>
    </html>